//package exception.pckge;
//
//public class Exception2 {
//	
//	
//	
//	void addition(){
//		
//		int a=10;
//		int b=0;
//		
//		
//		
//		try {
//		int c=a/b;
//		
//		
//		System.out.println(c);
//		
//		}catch(Exception e) {
//			
//			System.out.println("Exception handled");
//			
//			System.out.println(e);
//		}
//	}
//	
//
//	
//
//	public static void main(String[] args) {
//		
//		Exception2 obj=new Exception2();
//		
//		obj.addition();
//		
//		System.out.println("End of statement");
//	}
//	
//	
//	
//	
//	
//
//}
